import com.atlassian.jira.component.ComponentAccessor
import org.apache.log4j.Logger
import com.atlassian.jira.user.ApplicationUser
import com.atlassian.crowd.embedded.api.Group

def logit = Logger.getLogger("com.domain1.eu.logging")

def groups = [
"Artience",
"WPC SEOUL",
"WPC PL",
"global-wpl",
"WPC BR",
"WPC CN",
"GMC",
"RSC",
"SDS",
"Wisewire QA",
"global-wb",
"WMC PMO",
"P6 OPTS",
"WPC PL Managers",
"HQ Support Team",
"global-dmm",
"jira-administrators",
"CHEIL HQ",
"tse-lpm",
"tse-dmm",
"ssa-lpm",
"ssa-dmm",
"sme-lpm",
"sme-dmm",
"siel-dmm",
"siel-lpm",
"sge-dmm",
"sge-lpm",
"seuk-lpm",
"seuc-dmm",
"seuc-lpm",
"setk-lpm",
"setk-dmm",
"set-dmm",
"set-lpm",
"sesg-lpm",
"sesg-dmm",
"serom-dmm",
"serom-lpm",
"serc-dmm",
"serc-lpm",
"sepr-lpm",
"sepr-dmm",
"SEPOL Cheil",
"SEPOL Samsung",
"sepol-lpm",
"sepco-lpm",
"sepco-dmm",
"sepak-dmm",
"sepak-lpm",
"seo-lpm",
"seo-dmm",
"senz-lpm",
"senz-dmm",
"sena-lpm",
"semag-lpm",
"semag-dmm",
"sem-lpm",
"selv-dmm",
"selv-lpm",
"sela-lpm",
"sela-dmm",
"sece-lpm",
"sece-dmm",
"sein-dmm",
"sein-lpm",
"seil-dmm",
"seil-lpm",
"SESA Cheil",
"SEI Cheil",
"sei-lpm",
"sei-dmm",
"sehk-lpm",
"sehk-dmm",
"seh-dmm",
"seh-lpm",
"segr-lpm",
"segr-dmm",
"SEG Cheil",
"seg-lpm",
"seg-dmm",
"sef-dmm",
"sef-lpm",
"seeg-dmm",
"seeg-lpm",
"seda-lpm",
"seda-dmm",
"secz-lpm",
"sech-lpm",
"sech-dmm",
"seca-lpm",
"seca-dmm",
"SEBN Cheil",
"sebn-lpm",
"seb-lpm",
"seau-lpm",
"seasa-lpm",
"seasa-dmm",
"seag-lpm",
"sead-dmm",
"sead-lpm",
"SDSA",
"sea-dmm",
"scic-lpm",
"scic-dmm",
"savina-dmm",
"savina-lpm",
"sapl-lpm",
"sapl-dmm",
"samcol-lpm",
"ksa-lpm",
"ksa-dmm",
"iran-lpm",
"iran-dmm",
"SAMSUNG HQ",
"africa-lpm",
"africa-dmm",
"WSC Team",
"SEUK Cheil",
"SEUK Samsung",
"seuk-dmm",
"sepol-dmm",
"sena-dmm",
"sem-dmm",
"sesa-dmm",
"secz-dmm",
"seau-dmm",
"seas-dmm",
"samcol-dmm"
]

def groupManager = ComponentAccessor.groupManager
groups.each(){
Group groupIn = groupManager.getGroup(it)
if (groupIn) {
	//logit.info("source : " + groupIn.name)
		Collection<ApplicationUser> inUsers = groupManager.getUsersInGroup(groupIn)
    	inUsers.each(){
            if (it.getDirectoryId() == 1 || it.isActive() == false) {
               // ignore
            } else {
                def license = groupManager.isUserInGroup(it, "jira-software-users")
                if (license) {
        			logit.info( groupIn.getName()  + "," +it.displayName)
            	}
            }
    	}
	}
}
